version: "3.8"

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: vote_sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1q2w3e4r@#$
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - app

  vote:
    container_name: vote_app
    build:
      context: ./
      dockerfile: src/KubernetesHackathon.Vote/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+
      - ConnectionStrings__Default=Server=sqldata;Database=Hackathon;User Id=sa;Password=1q2w3e4r@#$;TrustServerCertificate=True;MultipleActiveResultSets=True;
    ports:
      - "5009:80"
    networks:
      - app
    depends_on:
      - sqldata

  admin:
    container_name: vote_admin
    build:
      context: ./
      dockerfile: src/KubernetesHackathon.Admin/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+
      - ConnectionStrings__Default=Server=sqldata;Database=Hackathon;User Id=sa;Password=1q2w3e4r@#$;TrustServerCertificate=True;MultipleActiveResultSets=True;
    ports:
      - "5011:80"
    networks:
      - app
    depends_on:
      - vote_app
      - sqldata

volumes:
  sqlvolume:

networks:
  app:
    driver: bridge
